#!/usr/bin/env bash
# Concatenate all handover migrations in order for a from-scratch apply.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
echo "-- GreenCoat / SaaSClinics full schema (handover concat)"
echo "-- Generated by apply-all.sh — review before executing on production."
echo ""
for f in "$ROOT"/migrations/*.sql; do
  echo ""
  echo "-- >>> BEGIN $(basename "$f")"
  cat "$f"
  echo ""
  echo "-- <<< END $(basename "$f")"
done
